
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('AC', 'Acre');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('AL', 'Alagoas');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('AP', 'Amapá');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('AM', 'Amazonas');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('BA', 'Bahia');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('CE', 'Ceará');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('DF', 'Distrito Federal');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('ES', 'Espírito Santo');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('GO', 'Goiás');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('MA', 'Maranhão');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('MT', 'Mato Grosso');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('MG', 'Minas Gerais');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('PA', 'Pará');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('PB', 'Paraíba');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('PR', 'Paraná');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('PE', 'Pernambuco');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('PI', 'Piauí');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('RO', 'Rondônia');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('RR', 'Roraima');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('SC', 'Santa Catarina');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('SP', 'São Paulo');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('SE', 'Sergipe');
INSERT INTO tbl_estados_brasileiros (sigla, descricao) VALUES ('TO', 'Tocantins');

INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (1, 'Japonesa', 'categoria-0001.jpg', 'capa-categoria-0001.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (2, 'Pizza', 'categoria-0002.jpg', 'capa-categoria-0002.jpeg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (3, 'Marmita', 'categoria-0003.jpg', 'capa-categoria-0003.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (4, 'Hamburger', 'categoria-0004.jpg', 'capa-categoria-0004.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (5, 'Salada', 'categoria-0005.jpg', 'capa-categoria-0005.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (6, 'Bebidas', 'categoria-0006.jpg', 'capa-categoria-0006.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (7, 'Sorvetes', 'categoria-0007.jpg', 'capa-categoria-0007.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (8, 'Italiana', 'categoria-0008.jpg', 'capa-categoria-0008.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (9, 'Carnes', 'categoria-0009.jpg', 'capa-categoria-0009.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (10, 'Açai', 'categoria-0010.jpg', 'capa-categoria-0010.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (11, 'Chinesa', 'categoria-0011.jpg', 'capa-categoria-0011.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (12, 'Brasileira', 'categoria-0012.jpg', 'capa-categoria-0012.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (13, 'Lanches', 'categoria-0013.jpg', 'capa-categoria-0013.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (14, 'Sobremesa', 'categoria-0014.jpg', 'capa-categoria-0014.jpg');
INSERT INTO tbl_categoria (id, descricao, url_imagem, url_capa) VALUES (15, 'Sanduíche', 'categoria-0015.jpg', 'capa-categoria-0015.jpg');